# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Qiu\Desktop\mess\sudoku_project\python\rules.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RulesWindow(object):
    def setupUi(self, RulesWindow):
        RulesWindow.setObjectName("RulesWindow")
        RulesWindow.resize(1110, 659)
        self.centralwidget = QtWidgets.QWidget(RulesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 1111, 631))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, -40, 661, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(50, 140, 1041, 451))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(28)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.rules_back = QtWidgets.QPushButton(self.centralwidget)
        self.rules_back.setGeometry(QtCore.QRect(60, 30, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.rules_back.setFont(font)
        self.rules_back.setObjectName("rules_back")
        RulesWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RulesWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 26))
        self.menubar.setObjectName("menubar")
        RulesWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RulesWindow)
        self.statusbar.setObjectName("statusbar")
        RulesWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RulesWindow)
        QtCore.QMetaObject.connectSlotsByName(RulesWindow)

    def retranslateUi(self, RulesWindow):
        _translate = QtCore.QCoreApplication.translate
        RulesWindow.setWindowTitle(_translate("RulesWindow", "MainWindow"))
        self.label.setText(_translate("RulesWindow", "游戏规则"))
        self.textEdit.setHtml(_translate("RulesWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bahnschrift SemiLight\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">游戏目标：</span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">数独是一款经典的数字填充游戏，玩家需要在一个 9x9 的网格中填写数字，使得每一行、每一列以及每个 3x3 宫内都包含 1 到 9 的数字，且每个数字不能重复。玩家可以选择</span><span style=\" font-size:14pt; font-weight:600;\">自动生成初盘</span><span style=\" font-size:14pt;\">或者</span><span style=\" font-size:14pt; font-weight:600;\">人工设置初盘</span><span style=\" font-size:14pt;\">，并且系统会检测人工设置的初盘是否合法。</span></p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">游戏模式：</span></h3>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">自动生成初盘</span>：系统会根据玩家选择的难度自动生成一个随机数独题目，题目包含一定数量的空格（根据难度设定，空格数目不同）。玩家需要在规定时间内填入数字，完成数独解题。</li>\n"
"<li style=\" font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">人工设置初盘</span>：玩家可以手动输入数独初盘，通过键盘在 9x9 的网格中设置初始数字。系统将自动检测设置的初盘是否合法，确保每行、每列和每个 3x3 宫内数字不重复。如果初盘不合法，系统会提示玩家重新设置。</li>\n"
"<li style=\" font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">求解数独</span>：游戏提供了一个自动求解功能，使用DPLL算法来计算数独的解。如果玩家卡住了，可以点击“求解”按钮查看完整的答案。</li></ol>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">游戏交互功能：</span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">检查</span>：当玩家填写完数独并点击“检查”按钮时，程序会标记出玩家填写正确和错误的数字。正确的答案会以绿色显示，错误的答案会以红色显示。几秒钟后，所有颜色恢复为默认状态。</li>\n"
"<li style=\" font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">偷看答案</span>：玩家可以在游戏过程中点击“偷看答案”按钮，系统会在十秒内展示完整的答案，并在十秒后自动恢复玩家的当前输入状态。</li>\n"
"<li style=\" font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">显示答案</span>：玩家可以选择在解题过程中查看完整的答案，程序将记录偷看答案的次数，并统计游戏的总用时。游戏结束时，系统会显示玩家的偷看次数以及总用时。</li></ul></body></html>"))
        self.rules_back.setText(_translate("RulesWindow", "返回"))
